name: Copy File on Commit

on: [push]

jobs:
  file-copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy file
        run: |
          cp src/raynodes/io/Importer.h include/
      - name: Commit file if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add include/Importer.h
          git commit -m "Updated include" || echo "No changes to commit"
          git push