name: CMake Build for Windows

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Cache CMake builds
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/build
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt', '**/*.cpp', '**/*.h') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Configure CMake
        run: cmake -B build -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DCMAKE_BUILD_TYPE=Release -DRN_ENABLE_SANITIZER=OFF -DRN_BUILD_TESTS=ON -S .
        working-directory: ${{ github.workspace }}
        shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

      - name: Build
        run: cmake --build build --config Release
        working-directory: ${{ github.workspace }}

      - name: Run Tests
        run: ctest -C Release --output-on-failure
        working-directory: ${{ github.workspace }}/build

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test Results
          path: ${{ github.workspace }}/build/Testing/**/*.xml